Modified the .gitlab-ci.yml file to test the docker image used in the dev deploy step exists in docker hub.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -143,6 +143,8 @@ dev:
     - |
       if [ ! -z ${KUBERNETES_ENDPOINT+set} ]; then
 
+        apk --no-cache --update add jq
+
         kubectl config set-cluster local --server="${KUBERNETES_ENDPOINT}"
         kubectl config set clusters.local.certificate-authority-data "${KUBERNETES_CERTIFICATE_AUTHORITY_DATA}"
         kubectl config set-credentials "${KUBERNETES_DEV_USER}" --token="${KUBERNETES_DEV_USER_TOKEN}"
@@ -154,7 +156,21 @@ dev:
         # Substitute the "latest" image tag in your deployment template with a more specific tag
         # and record the deployment so you can rollback to this particular version.
         #
-        sed -i "s/latest/${CI_COMMIT_SHA:0:12}/g" kube/dev/webapp/webapp-deployment.yaml
+        # Need to check that the docker image corresponding to this CI_COMMIT_SHA exists in Docker Hub.
+        # Scheduled turnover of the container can still run for a CI_COMMIT_SHA where the build fail to complete.
+
+        TOKEN=$( curl -sSLd "username=${DOCKER_HUB_USER}&password=${DOCKER_HUB_PSWD}" https://hub.docker.com/v2/users/login | jq -r ".token" )
+        JSON=$( curl -sH "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${DOCKER_HUB_USER}/${DOCKER_HUB_REPO}/tags/${CI_COMMIT_SHA:0:12}/")
+        IMAGE_TAG_NAME=$(echo $JSON | jq  -r '.name')
+
+        if [ "$IMAGE_TAG_NAME" = "${CI_COMMIT_SHA:0:12}" ]; then
+            # Substitute the "latest" image tag in your deployment template
+            sed -i "s/latest/${CI_COMMIT_SHA:0:12}/g" kube/dev/webapp/webapp-deployment.yaml
+        else
+            # DO NOT push out the latest tag to ensure rollback is possible.
+            exit 1
+        fi
+
         sed -i "s/STRING_REPLACED_DURING_REDEPLOY/$(date)/g" kube/dev/webapp/webapp-deployment.yaml
 
         if kubectl apply -f kube/dev/webapp/webapp-deployment.yaml --record | grep -q unchanged; then
